### ISSUE TITLE
Clarification on the reference strain used

### ISSUE THREAD

**Issue by LeonardosMageiros** [bioinfo-ut/PlasmidSeeker#14]
Hi!

I am trying to run PlasmidSeeker against a dataset that contains strains from different species of the same genus to investigate plasmid distribution across at the genus level. 

Would it be better to use a single reference strain for all the runs or I should use a different reference strain (that is closer to the specific species) every time I interrogate a different species. 

Could you conceptually explain how the reference strain is used by the algorithm so I can understand your response better? 

Thank you very much for all your help. 

Leonardos

**Comment by mihkelvaher** [comment]
Hi!

One of the goals for PlasmidSeeker is estimating the copy number per cell of the identified plasmid. Since there are multiple bacterial cells with multiple copies of plasmids in the sample we need the ratio of plasmid to genomic to get the copy number per cell estimate (assuming that the bacterial genome is 1 copy per cell). This is also the reason for the isolate requirement because in case of a mix of species we cannot say from which cell the plasmid originates and therefore cannot calculate the ratio and copy number.
Please refer to the paper for additional information (https://peerj.com/articles/4588/).

I can't see how using different bacterial reference genomes yields any meaningful abundance information because the same plasmid can be in different species in varying copy numbers resulting in a single signal which can't be separated.

That being said, choosing one species and running PlasmidSeeker should output which plasmids are in the sample. In this case all abundance info should be regarded critically or to be safe, discarded.

Hope it helps,
Mihkel

**Comment by LeonardosMageiros** [comment]
Mihkel thank you very much for your reply. 

I have to admit that I am still a bit confused. From your reply and your paper I understand that the reference chromosomal isolate given with the -b option should be as close as possible to the query isolate. 

So lets suppose I have 10 Klebsiella pneumoniae strains and 10 Klebsiella oxytoca strains that I want to interrogate using your algorithm. And lets suppose I want to use the abundance information for each plasmid. Then I should use a  Klebsiella pneumoniae reference strain for my 10 Klebsiella pneumoniae isolates and a Klebsiella oxytoca strain for the other 10 Klebsiella oxytoca strains. Do I get this correctly? 

What happens if I use the assembly of the query isolate itself as reference? Would that be a good practice as in my head this should be the perfect reference for the query isolate?  

Apologies for my confusion but I would like to make this clear so I can understand what I am doing. 

Thank you very much for your help. 
Leonardos

**Comment by mihkelvaher** [comment]
Hi

If you have a sample (1 fastq) containing only 1 strain then yes, you can use a Klebsiella pneumoniae reference strain for all 10 Klebsiella pneumoniae samples. The requirement is that there is only one strain in the mix. If the sample strains are quite different, you might need to identify a close reference strain for each of them individually (using for example http://bioinfo.ut.ee/strainseeker/).

Though the query isolate assembly might be the perfect reference (and this applies also to any reference), be sure that there are no plasmids in the assembly. If you'd just assemble the raw sequences without any cleaning, you will have plasmids in your assembly. Removing plasmid sequences might also prove a bit cumbersome, so I'd suggest identifying a suitable reference first and then running PlasmidSeeker.

If, on the other hand, you have a mix of different strains/species (all in one fastq), there are problems with estimating abundance as discussed above.

Mihkel

**Comment by martroosaare** [comment]
Plasmidseeker uses the closest bacterial genome to estimate bacterial genome coverage by looking at k-mers shared by your reads and the assembly. 

If you are using a remote strain, some of the k-mers from the bacterium in your reads would be missing from the remote one and some might be doubled. The more remote the assembly is, the more bias you introduce.

In short - using the same species as the closest strain should be OK for most purposes.
